# Generated by Django 4.1.4 on 2022-12-12 09:55

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/image/', verbose_name='Product Image')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('stock', models.PositiveIntegerField(verbose_name='Total Stock')),
                ('create_date', models.DateField(auto_now=True)),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('Condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.condition', verbose_name='Product Current Condition')),
                ('categories', models.ManyToManyField(to='products.categories', verbose_name='Categories')),
            ],
        ),
    ]
