# Generated by Django 4.1.4 on 2022-12-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Condition',
            new_name='condition',
        ),
    ]
