# Generated by Django 4.1.4 on 2022-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
