# Generated by Django 4.1.4 on 2022-12-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_total_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Clothe',
        ),
    ]
