# Generated by Django 4.1.4 on 2022-12-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_clothe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothe',
            new_name='Product',
        ),
    ]
