# Generated by Django 4.1.4 on 2022-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_clothe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Tags'),
        ),
    ]
