# Generated by Django 4.1.4 on 2022-12-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_myorder_is_order_delivered_myorder_is_order_placed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=range(1, 11)),
        ),
    ]
