# Generated by Django 4.1.4 on 2022-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_myorder_product_alter_myorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
