# Generated by Django 4.1.4 on 2022-12-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_myorder_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorder',
            old_name='user',
            new_name='my_user',
        ),
    ]
