# Generated by Django 4.1.4 on 2023-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
