# Generated by Django 4.1.4 on 2023-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_myorder_is_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
    ]
